### ISSUE TITLE
Weekdays seem to be off by one

### ISSUE THREAD

**Issue by datenhahn** [d-rk/cron-descriptor#1] opened 2018-07-10 15:39 UTC
![auswahl_433](https://user-images.githubusercontent.com/13999666/42521016-0f98de0c-8468-11e8-9984-d7647143571d.png)

http://www.quartz-scheduler.org/documentation/quartz-2.x/tutorials/crontrigger.html

From the Documentation:

```
0 15 10 ? * 6L 2002-2005 | Fire at 10:15am on every last friday of every month during the years 2002,             2003, 2004 and 2005
-- | --
```

**Comment by d-rk** [comment] 2018-07-10 18:44
perhaps this is caused by Monday as start of week instead of Sunday.
I have to check if I can fix it or if it has to be fixed in the library that I'm using for generation of the description.

**Comment by d-rk** [comment] 2018-10-02 17:38
the latest release should fix the issue.
see: https://github.com/random-dwi/cron-descriptor/commit/cce379be6327c7affb4d2daa36ae0f7312465a35

**Closed as completed by d-rk** 2018-10-02 17:38 UTC
